<template>
    <div class="bg-slate-500 h-12 py-2 px-3 lg:px-6 flex items-center justify-between text-white">
    <p class="text-sm lg:text-lg font-semibold">ANI-GPT</p>
    <NuxtLink to="https://voicevox.hiroshiba.jp/" target="_blank">
      <div class="w-42 p-2">
        <div class="flex items-center">
          <p class="text-xs ml-2 flex items-center">
            Voice generated by VOICEVOX
          </p>
          <div class="w-5 ml-1">
            <img src="https://pbs.twimg.com/profile_images/1467890929365557248/Hk0-nRou_400x400.png" alt="VOICEVOX_LOGO" />
          </div> 
        </div>
      </div>
    </NuxtLink>
  </div>
</template>